use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    let chip_ws63 = env::var_os("CARGO_FEATURE_CHIP_WS63").is_some();
    let chip_bs21 = env::var_os("CARGO_FEATURE_CHIP_BS21").is_some();
    let bundled_memory = env::var_os("CARGO_FEATURE_BUNDLED_MEMORY_X").is_some();
    let boot_header_enabled = env::var_os("CARGO_FEATURE_BOOT_HEADER").is_some();
    let riscv_rt_start_experiment = env::var_os("CARGO_FEATURE_RISCV_RT_START_EXPERIMENT").is_some();

    if chip_ws63 && chip_bs21 {
        panic!("hisi-riscv-rt features `chip-ws63` and `chip-bs21` are mutually exclusive");
    }
    if boot_header_enabled && !chip_ws63 {
        panic!("hisi-riscv-rt `boot-header` is WS63-only; enable `chip-ws63` or disable it");
    }
    if riscv_rt_start_experiment && !chip_ws63 {
        panic!("hisi-riscv-rt `riscv-rt-start-experiment` is currently WS63-only");
    }

    let memory_x = Path::new("linker/ws63/memory.x");
    let layout_ld = Path::new("linker/ws63/layout.ld");
    let symbols_x = Path::new("linker/common/riscv-rt-symbols.x");
    let boot_header_x = Path::new("linker/ws63/boot-header.x");
    let startup_s = Path::new("asm/ws63/startup.S");

    println!("cargo:rerun-if-changed={}", memory_x.display());
    println!("cargo:rerun-if-changed={}", layout_ld.display());
    println!("cargo:rerun-if-changed={}", symbols_x.display());
    println!("cargo:rerun-if-changed={}", boot_header_x.display());
    println!("cargo:rerun-if-changed={}", startup_s.display());

    let layout_out = out_dir.join("layout.ld");
    let memory_out = out_dir.join("memory.x");
    let stale_device_out = out_dir.join("device.x");
    let symbols_out = out_dir.join("riscv-rt-symbols.x");

    // WS63 can use the bundled memory map. BS2X examples deliberately provide
    // their own BS20/BS21 memory.x; copying the WS63 one there would create two
    // competing MEMORY facts on the linker search path.
    if bundled_memory && chip_ws63 {
        fs::copy(memory_x, &memory_out).expect("Failed to copy WS63 memory.x");
    }

    // The current BS2X compatibility adapter still reuses this linker layout with
    // a BS2X-supplied memory.x. A dedicated BS2X layout can replace this at the
    // adapter seam without changing downstream build scripts.
    fs::copy(layout_ld, &layout_out).expect("Failed to copy layout.ld");

    // Chip-specific `device.x` files are owned by the active PAC's `rt` feature
    // (ws63-pac/rt or bs2x-pac/rt). This crate's entry script still INCLUDEs
    // `device.x`, but it deliberately does not copy one into its own OUT_DIR.
    if stale_device_out.exists() {
        fs::remove_file(&stale_device_out).expect("Failed to remove stale runtime-owned device.x");
    }
    fs::copy(symbols_x, &symbols_out).expect("Failed to copy riscv-rt-symbols.x");

    if boot_header_enabled {
        let boot_header_out = out_dir.join("boot-header.x");
        fs::copy(boot_header_x, &boot_header_out).expect("Failed to copy boot-header.x");
    }

    // Downstream binaries opt in with one neutral entry script name:
    // `-Thisi-riscv-link.x`. `ws63-link.x` remains as a temporary compatibility
    // alias for older examples and external applications.
    let link_out = out_dir.join("hisi-riscv-link.x");
    let compat_link_out = out_dir.join("ws63-link.x");
    let mut link_contents = String::from("/* Auto-generated by hisi-riscv-rt/build.rs. */\n");
    link_contents.push_str(
        "INCLUDE memory.x\n\
         INCLUDE layout.ld\n\
         INCLUDE device.x\n\
         INCLUDE riscv-rt-symbols.x\n",
    );
    if boot_header_enabled {
        link_contents.push_str("INCLUDE boot-header.x\n");
    }
    fs::write(&link_out, &link_contents).expect("Failed to write hisi-riscv-link.x");

    let mut compat_contents = String::from("/* Deprecated compatibility alias. Use -Thisi-riscv-link.x instead. */\n");
    compat_contents.push_str(&link_contents);
    fs::write(&compat_link_out, compat_contents).expect("Failed to write ws63-link.x");

    println!("cargo:rustc-link-search={}", out_dir.display());

    println!("cargo:rustc-env=RISCV_RT_BASE_ISA=rv32i");

    if chip_ws63 {
        println!("cargo:rustc-cfg=target_chip=\"ws63\"");
    } else if chip_bs21 {
        println!("cargo:rustc-cfg=target_chip=\"bs2x\"");
    }
}
