/// Build script for hisi-riscv-rt.
///
/// Copies linker scripts and device.x to OUT_DIR so they can be
/// referenced by the linker and runtime code.
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // Copy linker scripts for the linker
    let memory_x = Path::new("memory.x");
    let layout_ld = Path::new("layout.ld");
    let device_x = Path::new("device.x");
    let symbols_x = Path::new("riscv-rt-symbols.x");

    println!("cargo:rerun-if-changed=memory.x");
    println!("cargo:rerun-if-changed=layout.ld");
    println!("cargo:rerun-if-changed=device.x");
    println!("cargo:rerun-if-changed=riscv-rt-symbols.x");
    println!("cargo:rerun-if-changed=boot-header.x");
    println!("cargo:rerun-if-changed=asm/startup.S");

    // Place linker scripts in OUT_DIR and use absolute paths
    let layout_out = out_dir.join("layout.ld");
    let memory_out = out_dir.join("memory.x");
    let device_out = out_dir.join("device.x");
    let symbols_out = out_dir.join("riscv-rt-symbols.x");

    // memory.x is bundled only when the `bundled-memory-x` feature is on (default).
    // A downstream binary with `default-features = false` supplies its own memory.x
    // (on its own link-search path), so we must NOT also drop ours — that would put
    // two `memory.x` on the path and make `INCLUDE memory.x` order-dependent.
    if env::var_os("CARGO_FEATURE_BUNDLED_MEMORY_X").is_some() {
        fs::copy(memory_x, &memory_out).expect("Failed to copy memory.x");
    }
    fs::copy(layout_ld, &layout_out).expect("Failed to copy layout.ld");
    // device.x carries the WS63 interrupt vector names. Under chip-bs21 the BS21
    // vectors come from bs2x-pac's device.x (its rt feature), so we must NOT also
    // drop the WS63 one — that would put two `device.x` on the path and make
    // `INCLUDE device.x` order-dependent (WS63 names vs BS21 names).
    if env::var_os("CARGO_FEATURE_CHIP_WS63").is_some() {
        fs::copy(device_x, &device_out).expect("Failed to copy device.x");
    }
    fs::copy(symbols_x, &symbols_out).expect("Failed to copy riscv-rt-symbols.x");

    // boot-header (default OFF): when the `boot-header` feature is on, drop the
    // boot-header.x fragment into OUT_DIR and INCLUDE it. It places the 0x300-byte
    // `.boot_header` section (src/boot_header.rs's BOOT_HEADER static) at flash
    // 0x230000 so it ends exactly where .startup begins at ORIGIN(PROGRAM)=0x230300,
    // making the bare ELF directly bootable (no `hisi-fwpkg image` step). When the
    // feature is off this fragment is neither copied nor INCLUDEd, so the layout is
    // byte-unchanged.
    let boot_header_enabled = env::var_os("CARGO_FEATURE_BOOT_HEADER").is_some();
    if boot_header_enabled {
        let boot_header_x = Path::new("boot-header.x");
        let boot_header_out = out_dir.join("boot-header.x");
        fs::copy(boot_header_x, &boot_header_out).expect("Failed to copy boot-header.x");
    }

    // Single entry script that INCLUDEs the linker scripts in the required order
    // (layout → memory → device → symbols, with boot-header first when on).
    // Downstream binaries opt in with one `-Tws63-link.x` (see
    // ws63-examples/blinky/build.rs).
    let link_out = out_dir.join("ws63-link.x");
    // Order matters: MEMORY (memory.x) must precede the SECTIONS that reference its
    // regions (layout.ld); device.x PROVIDEs reference layout symbols, so it follows;
    // riscv-rt symbol defaults come last. boot-header.x (when enabled) is INCLUDEd
    // first — its absolute-address `.boot_header` output section is merged into the
    // final SECTIONS and does not depend on memory.x's MEMORY {} block.
    let mut link_contents = String::from(
        "/* Auto-generated by hisi-riscv-rt/build.rs. Entry linker script for WS63 binaries. */\n",
    );
    link_contents.push_str(
        "INCLUDE memory.x\n\
         INCLUDE layout.ld\n\
         INCLUDE device.x\n\
         INCLUDE riscv-rt-symbols.x\n",
    );
    // boot-header.x is INCLUDEd LAST: its `.boot_header` output section is placed
    // at the absolute address 0x230000 (inside FLASH), independent of layout.ld's
    // regions. Including it after layout.ld keeps layout.ld's ordering of the
    // PROGRAM sections (.startup/.text/orphans like .eh_frame) established first, so
    // the absolute-addressed header does not perturb lld's orphan-section placement.
    if boot_header_enabled {
        link_contents.push_str("INCLUDE boot-header.x\n");
    }
    fs::write(&link_out, link_contents).expect("Failed to write ws63-link.x");

    // Expose OUT_DIR as a linker search path. Unlike `rustc-link-arg`, a
    // `rustc-link-search` from a *library* dependency DOES propagate to the
    // downstream binary's link, so `-Tws63-link.x` (and the INCLUDEs inside it)
    // resolve against this directory.
    println!("cargo:rustc-link-search={}", out_dir.display());

    // (startup.S is now included via global_asm! in lib.rs)

    // Set RISC-V base ISA for riscv-rt (rv32i — no atomic extension)
    println!("cargo:rustc-env=RISCV_RT_BASE_ISA=rv32i");

    // Custom cfg for WS63-specific code
    println!("cargo:rustc-cfg=target_chip=\"ws63\"");
}
